spring:
    application:
        name: Java17demo

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://154.89.148.95:3306/ch_website?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: cch
        password: Cch2233.
        type: com.alibaba.druid.pool.DruidDataSource
    servlet:
        #upload test
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
            enabled: true

    data:
        redis:
            host: localhost
            #172.25.1.159
            port: 6379
            database: 0 #Redis数据库索引（默认为0）
            timeout: 5000 #连接超时时间
            lettuce:
                shutdown-timeout: 500
            jedis:
                pool:
                    max-active: 50 #连接池最大连接数（使用负值表示没有限制）
                    max-wait: 3000 #连接池最大阻塞等待时间（使用负值表示没有限制）
                    max-idle: 20 #连接池中的最大空闲连接
                    min-idle: 2 #连接池中的最大空闲连接

server:
    port: 9090

# 自定义配置
image-url: http://localhost:9090/

# MyBatis配置
mybatis:
    mapper-locations: classpath*:com/example/java17demo/mapper/*.xml
    type-aliases-package: com.example.java17demo.pojo
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        # 开启 MyBatis 日志

logging:
    level:
      com.example.java17demo: TRACE
# 滑块验证码配置, 详细请看 cloud.tianai.captcha.autoconfiguration.ImageCaptchaProperties 类
captcha:
    # 如果项目中使用到了redis，滑块验证码会自动把验证码数据存到redis中, 这里配置redis的key的前缀,默认是captcha:slider
    prefix: captcha
    # 验证码过期时间，默认是 2 分钟,单位毫秒, 可以根据自身业务进行调整
    expire:
        # 默认缓存时间 2分钟
        default: 10000
        # 针对 点选验证码 过期时间设置为 2分钟, 因为点选验证码验证比较慢，把过期时间调整大一些
        WORD_IMAGE_CLICK: 20000
    # 使用加载系统自带的资源, 系统的默认资源包含滑动验证码模板和旋转验证码模板
    init-default-resource: true
    # 缓存控制, 默认为false不开启
    local-cache-enabled: true
    # 验证码会提前缓存一些生成好的验证数据, 默认是20
    local-cache-size: 20
    # 缓存拉取失败后等待时间 默认是 5秒钟
    local-cache-wait-time: 5000
    # 缓存检查间隔 默认是2秒钟
    local-cache-period: 2000
    # 配置字体库，文字点选验证码的字体库，可以配置多个
    font-path:
        - classpath:font/SimHei.ttf
    secondary:
        # 二次验证, 默认false 不开启
        enabled: false
        # 二次验证过期时间, 默认 2 分钟
        expire: 120000
        # 二次验证缓存key前缀，默认是 captcha:secondary
        keyPrefix: "captcha:secondary"